### ISSUE TITLE
Config to init hooks

### ISSUE THREAD

**Issue by cvergne** [tarampampam/webhook-tester#138]
Hi,

First, thanks for that project, it works like a charm !
I've been looking for a self-hosted alternative to Pipedream/request-bin for a while without success, then by looking on webhook.site I found your project which is running great as a single docker image :)

I would like to suggest a feature to init some hooks endpoint from a config file.
Because when running the tester, URLs are self generated so we can't know automatically what the endpoint will be. So the point would be to have like a JSON or YAML config file with the list of named endpoint we want.

~~If not, is there a way to programmatically create an endpoint and get the endpoint URL as response ? (CLI or API)~~
edit: I've found I can call `/api/session` to create a new endpoint :)

Thanks.

**Comment by tarampampam** [comment]
You'r welcome! 😀
