### ISSUE TITLE
Any way to run app not at root of site?

### ISSUE THREAD

**Issue by TechplexEngineer** [tarampampam/webhook-tester#159]
I'd like the app to be available at http://<my_ip>/webhook

Is there any way to set a Base URL for the web assets?

**Comment by tarampampam** [comment]
Currently no, but you can make a PR with the required functionality! 🤝

**Comment by tarampampam** [comment]
Friendly ping @TechplexEngineer

**Comment by TechplexEngineer** [comment]
Hey, thanks for making this change! I'll try to test it this week. I ended up going another direction and setting up a subdomain for the proxy

**Comment by TechplexEngineer** [comment]
Looks great, thanks for making the change!

**Comment by tarampampam** [comment]
All works fine?

**Comment by tomaxsas** [comment]
backend can be under any path prefix, but frontend not. react errors out with route error, index.html has links to js and assests under root. after manually fiddling with ui js file, managed to get it nearly working 100%, some redirects till does not work.
