### ISSUE TITLE
Question: Persist Webhook URL

### ISSUE THREAD

**Issue by michaelgroeger** [tarampampam/webhook-tester#160]
Hi tarampampam,

First of all big thanks to this great project. It is really helpful to debug webhooks.

Currently, I have webhook-tester deployed in a docker-compose along the tools which send their webhooks to the webhook-tester. 

When I take the docker-compose down and bring it up again i receive a new Webhook Url which I then need to reconfigure in the other tools. Is there a way to persist the Webhook Url from previous runs?

Thank you very much!

**Comment by tarampampam** [comment]
Hi! Glad to hear that!

At this moment I haven't enough free time for this feature, sorry for that... But it sounds really useful! Maybe later I will implement it, ok?

**Comment by f5oto** [comment]
+1 for this feature.
Simple persistent volume and persistent webhook rul would be amazing.

**Comment by tarampampam** [comment]
Sorry for the late response, but I have good news - this feature was implemented successfully!
