### ISSUE TITLE
Slow Loading multipart/form-data

### ISSUE THREAD

**Issue by hirenshah** [tarampampam/webhook-tester#306]
When requests are multipart/form-data clicking on and off them is quite slow because the all the data is displayed. Would it be possible to have it only load when the user clicks on the Text or Binary buttons?

**Comment by hirenshah** [comment]
I tried making this code change myself and suffice to say, I failed miserably 🤦🏻‍♂️

**Comment by tarampampam** [comment]
Could you test the fix? The docker tag is `ghcr.io/tarampampam/webhook-tester:issue-306`

**Comment by hirenshah** [comment]
> Could you test the fix? The docker tag is [`ghcr.io/tarampampam/webhook-tester:issue-306`](https://github.com/tarampampam/webhook-tester/pkgs/container/webhook-tester/96433435?tag=issue-306)

It works perfectly :)
