### ISSUE TITLE
Add option to customize server response payload and status code

### ISSUE THREAD

**Issue by gabrielboliveira** [tarampampam/webhook-tester#333]
In some scenarios, it would be amazing to customize what the server returns. For example: 

- Customize what the server replies with, adding a custom JSON payload. 
- Customize the Status Code, for example 204, 401, 404, 500, etc.

**Comment by tarampampam** [comment]
![image](https://github.com/tarampampam/webhook-tester/assets/7326800/7e8469d6-4ca7-46eb-b853-88128a1c2f0e)

![image](https://github.com/tarampampam/webhook-tester/assets/7326800/c631f802-7cac-4c1a-9f52-a0174d8385ce)

Is that what you need?

**Comment by gabrielboliveira** [comment]
Yes, exactly! Sorry, I didn't see that in the docs. That works great.
