### ISSUE TITLE
MAX_REQUESTS Environment Variable

### ISSUE THREAD

**Issue by hirenshah** [tarampampam/webhook-tester#334]
Does setting a MAX_REQUESTS Environment Variable actually work?  I have it set to 10000 but have noticed I only have the last 128 requests, which is the default amount

I've kept the Environment Variable as is and added `--max-requests 10000` in the command, and now it stores more than 128.

I'm using the CREATE_SESSION Environment Variable and that works as expected so I don't think it is an issue with how the Environment Variables are picked up.

**Comment by tarampampam** [comment]
```bash
$ docker run --rm -p 8080:8080/tcp tarampampam/webhook-tester serve --max-requests 512

08:27:32	info	Server starting	{"addr": "0.0.0.0", "port": 8080, "max requests": 512, "session ttl": "168h0m0s", "ignore prefixes": [], "storage driver": "memory", "pub/sub driver": "memory", "max websocket clients": 0, "single websocket ttl": "0s"}

$ docker run --rm -p 8080:8080/tcp -e "MAX_REQUESTS=10000" tarampampam/webhook-tester serve

08:27:52	info	Server starting	{"addr": "0.0.0.0", "port": 8080, "max requests": 10000, "session ttl": "168h0m0s", "ignore prefixes": [], "storage driver": "memory", "pub/sub driver": "memory", "max websocket clients": 0, "single websocket ttl": "0s"}
```

As I can see - yes, it works as expected O_o

**Comment by hirenshah** [comment]
Weird. I know Portainer on Synology sometimes has issues updating Environment Variables and therefore it has to be done via the Synology UI. Guessing it's down to that.
