### ISSUE TITLE
Create sessions "on the fly"

### ISSUE THREAD

**Issue by m-hume** [tarampampam/webhook-tester#559]
Hi
Would it be possible to generate sessions on the fly?
eg any request to a session ID that does not exist, creates that session ID and then performs that request.

I've never programmed in go but from what i can tell it would need session generation in the following functions
https://github.com/tarampampam/webhook-tester/blob/b6821d7fc959384ce4290fe0f97738f41c852c77/internal/http/handlers/api_session.go#L146
https://github.com/tarampampam/webhook-tester/blob/b6821d7fc959384ce4290fe0f97738f41c852c77/internal/http/handlers/api_session.go#L202

I'll have a play and see if i can make the changes and compile it myself
Thanks

**Comment by tarampampam** [comment]
Hello! Apologies for the late response, but I have good news - I've added the requested feature, along with a number of other improvements I made while working on version 2 of the app.

It would be great if you could try out the early test build and share your feedback. Do all the features work as expected? Did you encounter any crashes, or notice anything that isn’t functioning as intended?

The Docker image and precompiled binary files are available at this link: https://github.com/tarampampam/webhook-tester/releases/tag/v2.0.0-alpha1
