### ISSUE TITLE
Extra noise in logs with HealthChecker

### ISSUE THREAD

**Issue by sasha-simplyture** [tarampampam/webhook-tester#575]
Hi @tarampampam! Thank you for doing a great job!

Unfortunately, I'm still getting a lot of logs with health checks. I'm using the [latest docker image](https://hub.docker.com/layers/tarampampam/webhook-tester/1.1.0/images/sha256-b103f3348988cb63623bf2402463efb752819e0415a6266c25253176e8e52a10?context=explore):
```
{"level":"info","ts":1727796538.6479125,"msg":"HTTP request processed","remote addr":"127.0.0.1","useragent":"HealthChecker/internal","method":"GET","uri":"/live","status code":200,"duration":0.000021321}
```

**Comment by tarampampam** [comment]
Check out the new release [v2.0.0](https://github.com/tarampampam/webhook-tester/releases/tag/v2.0.0) (or a later version). If you encounter any errors or unexpected behavior, feel free to open a new issue. I'll be closing this one :)
