### ISSUE TITLE
Hardcoded/static URL GUID option

### ISSUE THREAD

**Issue by opsdisk** [tarampampam/webhook-tester#614]
Thanks for making this!

For testing, I don't want to have to switch between generating a unique URL GUID and my tool...I'd rather have it be static. 
 Something like:

`http://127.0.0.1:4430/11111111-2222-3333-4444-555555555555` will always be accepted by webhook-tester.

Maybe it could be a CLI switch like `--static-guid 11111111-2222-3333-4444-555555555555`?

**Comment by tarampampam** [comment]
May I ask if the automatic creation of sessions can be used instead of hardcoded session UUIDs? If not, could you please explain why?

**Comment by opsdisk** [comment]
My bad, I didn't understand what that switch did.  Works perfectly now!

**Comment by tarampampam** [comment]
No, it’s on me. I’ll improve the docs as soon as possible
