### ISSUE TITLE
Pretty print JSON request body 

### ISSUE THREAD

**Issue by SaintSimmo** [tarampampam/webhook-tester#78]
Currently, JSON request bodies (from a POST request, for example) are displayed in a single, horizontally scrollable code block (wraps by default on Safari).

Making use of `JSON.stringify` - or some other method - to pretty print JSON bodies in a more readable way would be a helpful improvement. 

Thanks for the great project!

**Comment by tarampampam** [comment]
💥 Released in [v0.3.1](https://github.com/tarampampam/webhook-tester/releases/tag/v0.3.1), thank you!
